apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  database-url: postgres://postgres:postgres@postgres:5432/ktaxes?sslmode=disable
  admin-username: adminTax
  admin-password: admin!