apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: migrate/migrate
        command: ["/bin/sh", "-c"]
        args:
          - migrate -database '$(DATABASE_URL)' -path /db/migrations up
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: database-url
        volumeMounts:
        - name: migrations
          mountPath: /db/migrations
      restartPolicy: OnFailure
      volumes:
      - name: migrations
        configMap:
          name: migration-scripts
  backoffLimit: 4